name: Pylint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12.3
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        pip install pylint pandas plotly dash pandas_ta

    - name: Run pylint
      run: |
         cd stock_analysis && PYTHONPATH=. pylint **/*.py --ignore=games,tests --disable=too-many-locals --fail-under=8.0
